server:
  port: ${PORT:8080}
spring:
  profiles:
    active: '@spring.profiles.active@'
  mail:
    host: smtp.gmail.com
    port: 587
    username: museitcorp@gmail.com
    password: dlcxaqvwxprvlzqc
    properties:
      mail:
        starttls:
          enable: true
        smtp:
          starttls:
            enable: true
          auth: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/museit}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASS:1234}
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: create
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:./static
museit:
  api:
    music-generation:
      url: https://museitharm.herokuapp.com
app:
  jwt:
    secret: ${JWT_SECRET:ProjAppRenSecretCode}
    expirationMs: 30000000
    refreshExpirationMs: 60000
