server:
  port: ${PORT:8080}
spring:
  datasource:
    password:
    url: jdbc:postgresql://localhost:5432/registration?currentSchema=public&user=postgres&password=Pudge
    username:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: museitcorp@gmail.com
    password: dlcxaqvwxprvlzqc
    properties:
      mail:
        starttls:
          enable: true
        smtp:
          starttls:
            enable: true
          auth: true
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:./static
museit:
  api:
    music-generation:
      url: https://museitharm.herokuapp.com
