server:
  port: ${PORT:8080}

spring:
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:./static
museit:
  api:
    music-generation:
      url: https://museitharm.herokuapp.com
