server:
  port: ${PORT:8080}
spring:
  profiles:
    active: '@spring.profiles.active@'
  mail:
    host: smtp.gmail.com
    port: 587
    username: museitcorp@gmail.com
    password: dlcxaqvwxprvlzqc
    properties:
      mail:
        starttls:
          enable: true
        smtp:
          starttls:
            enable: true
          auth: true
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:./static
museit:
  api:
    music-generation:
      url: https://museitharm.herokuapp.com
