server:
  port: ${PORT:8080}

spring:
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:./static
museit:
  api:
    music-generation:
      url: http://127.0.0.1:5000/api/file
